import { FC, ReactNode } from "react";
interface LayoutProps {
  children: ReactNode;
}
export const metadata = {
  title: "code with shdbccvhksgp",
  description: "Generated by create next app",
};

const Layout: FC<LayoutProps> = ({ children }) => {
  return <div className="bg-blue-100 h-screen">{children}</div>;
};
export default Layout;
